### ISSUE TITLE
Which versions of CASA to support?

### ISSUE THREAD

**Issue by e-koch** [Astroua/AstroCompute_Scripts#6]
There are issues with package installation on CASA 4.5/4.6 (see [here](https://github.com/astropy/astropy/pull/4840)). We should probably limit support to 4.3/4.4, at least until 4.7 is released later this year.

**Comment by tetarenk** [comment]
okay, although i have been running the timing script within casa-4.6 recently and I have not had any issues.

**Comment by e-koch** [comment]
Oh ok. I guess we don't need to update the astropy version in 4.6 then, which is the real issue.
